### PR TITLE
Login register fix

### PR DESCRIPTION
**Pull request by Conor-Behard333**
To Test:
- Create a user using the registration form
- With an admin account check the new user is in the user group
- Do the same with SSO
- Change the username of the SSO account
- try creating a user with the same name as the SSO account (should display a message saying username is already taken)
- try creating a user with the same name but different capitalization, for example, CoNor instead of Conor, as the SSO account  (should display a message saying username is already taken)

Details:
- When a user logs in with SSO they are assigned a random username which can then be changed
- When a user registers their name is checked properly (for example, a user with the name conor can't create a user with the username cOnor)
- when a user registers with the registration form and SSO they are added to the 'user' group
- removed the ability to change your email as we don't want this to be possible
- In the register form the first name and last name has been added as a field
- re-formated code

### CODE REVIEW

**Comment by Conor-Behard333** [comment]
[Add users to 'user' group when registered](https://trello.com/c/qJhqs0Hh/91-add-users-to-user-group-when-registered)

**Comment by Conor-Behard333** [comment]
[Make usernames unique](https://trello.com/c/7hRaHeUl/90-make-usernames-unique)

**Comment by MichaelHills01** [comment]
When creating an account using registration form, error "Group matching query does not exist."

**Comment by MichaelHills01** [comment]
Change redirect when username taken to register page (goes back to login atm)

**Review by MichaelHills01 — APPROVED** [review]

**Pull request merged**
